---
- name: Deploying nginx webserver
  hosts: nginx_nodes
  become: yes
  tasks:
    - name: Install nginx latest version and start service
      apt:
       name: nginx
       state: latest
    - name: Start nginx service
      ansible.builtin.service:
       name: nginx
       state: started
    - name: Reload nginx webserver
      ansible.builtin.service:
       name: nginx
       state: reloaded