---
- name: Deploying nginx webserver
  hosts: nginx_nodes
  become: yes
  tasks:
    - name: Call Firewalld Roles
      roles:
        - firewalld
    - name: Install nginx latest version and start service
      apt:
        name: nginx
        state: latest
    - name: Start nginx service
      service:
        name: nginx
        state: started
    - name: Reload nginx webserver
      service:
        name: nginx
        state: reloaded
    - name: Copy index.html
      template: 
        src: ~/files/index.html 
        dest: /usr/share/nginx/html/index.html 
        mode: 0644
    - name: Restart NGINX Service
      service:
        name: nginx
        state: restarted
