---
- name: Config-Firewal
  tasks:
  - name: FirewallD rules
    firewalld:
      permanent: yes
      immediate: yes
      service: "{{ item }}"
      state: enabled
    with_items:
      - http
      - https
