---
- name: Config-Firewal
  hosts: all
  tasks:
  - name: FirewallD rules
    firewalld:
      permanent: yes
      immediate: yes
      service: {{ item }}
      state: enabled
    with_items:
      - http
      - https
