---
- name: Config Firewal
  tasks:

  - name: Install firewalld if not Installed
    become: yes
    yum:
      name: firewalld
      state: present
  
  - name: Start and Enabled firewalld
    become: yes
    service:
      name: firewalld
      state: started
      enabled: yes

  - name: FirewallD rules
    firewalld:
      permanent: yes
      immediate: yes
      port: "{{item.port}}/{{item.proto}}"
      state: "{{item.state}}"
    loop:
     - {port: "80", proto: "tcp", state: "enabled"}
     - {port: "443", proto: "tcp", state: "enabled"}
    
  - name: Restart firewalld
    become: yes
    service: 
      name: firewalld
      state: restarted

